#!/bin/bash
#
# name        : conflib
# description : Ubuntu server toolbox configuration script library.
#
# 2010-01-21 daniele.denti@bluewin.ch 1.0
# 2012-10-27 daniele.denti@bluewin.ch 1.1 bug fix apache_james_v2
#                                         SUN java installation removed.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
# $1 the repository to add
#
add_apt_repository () {
  if [ -x add-apt-repository ]; then
    apt-get install python-software-properties --yes --quiet
  fi
  check_apt_repository "$1"
  if [ "$?" != "0" ]; then
    add-apt-repository "$1"
    apt-get update --yes --quiet
  fi
}

# add and configure apache James v2
apache_james_v2 () {

  get_java_home
  log_action_begin_msg "Looking for JAR binary"
  JAR=${JAVA_HOME}/bin/jar
  if [ -x ${JAR} ]; then
    log_action_end_msg 0
  else
    log_action_end_msg 1 "Cannot execute ${JAR}"
    exit 1
  fi 
  

  if [ ! -d /home/james/james-2.3.2 ]; then
    log_action_begin_msg "Apache James: download software"
     
    wget -O /tmp/apache-james-2.3.2.zip -t 3 -T 2 http://www.apache.org/dist/james/server/apache-james-2.3.2.zip
    if [ "$?" != "0" ]; then
      log_action_end_msg 1 "download failed"
    fi
  
    fgrep -e james /etc/passwd
    if [ "$?" != "0" ]; then
      useradd -c "Apache James file owner" -m -s /bin/bash james
    fi
  
    cd /home/james
    if [ ! -x /usr/bin/unzip ]; then
      apt-get install unzip --yes --quiet
    fi
    sudo -u james unzip /tmp/apache-james-2.3.2.zip
  fi
  
  log_action_begin_msg "Apache James: create folders"
  
  if [ ! -d /var/mail/error ]; then
    mkdir -p /var/mail/error
    chown -R james:james /var/mail/error
  fi
  if [ ! -d /var/mail/inboxes ]; then
    mkdir -p /var/mail/inboxes
    chown -R james:james /var/mail/inboxes
  fi
  if [ ! -d /var/mail/outgoing ]; then
    mkdir -p /var/mail/outgoing
    chown -R james:james /var/mail/outgoing
  fi
  if [ ! -d /var/users ]; then
    mkdir -p /var/users
    chown -R james:james /var/users
  fi
  if [ ! -d /var/mail/spool ]; then
    mkdir -p /var/mail/spool
    chown -R james:james /var/mail/spool
  fi
  if [ ! -d /var/nntp/groups ]; then
    mkdir -p /var/nntp/groups
    chown -R james:james /var/nntp/groups
  fi
  if [ ! -d /var/nntp/temp ]; then
    mkdir -p /var/nntp/temp
    chown -R james:james /var/nntp/temp
  fi
  if [ ! -d /var/nntp/articleid ]; then
    mkdir -p /var/nntp/articleid
    chown -R james:james /var/nntp/articleid
  fi
  if [ ! -d /var/nntp/spool ]; then
    mkdir -p /var/nntp/spool
    chown -R james:james /var/nntp/spool
  fi
  log_action_end_msg 0
  
  log_action_begin_msg "Apache James: configure"

  cd /home/james/james-2.3.2
  if [ ! -d /home/james/james-2.3.2/apps/james ]; then
    sudo -u james mkdir -p /home/james/james-2.3.2/apps/james
  fi
  cd apps/james
  sudo -u james ${JAR} -xvf /home/james/james-2.3.2/apps/james.sar SAR-INF/config.xml >/dev/null
  
  sed -i s/'enableForwarding="true"'/'enableForwarding="false"'/g SAR-INF/config.xml
  sed -i s/'<port>110<\/port>'/'<port>4110<\/port>'/g SAR-INF/config.xml
  sed -i s/'<port>25<\/port>'/'<port>2525<\/port>'/g SAR-INF/config.xml
  sed -i s/'<port>119<\/port>'/'<port>4119<\/port>'/g SAR-INF/config.xml
  sed -i s/'<authorizedAddresses>127.0.0.0\/8<\/authorizedAddresses>'/'<authorizedAddresses>127.0.0.0\/8,192.168.1.0\/24<\/authorizedAddresses>'/g SAR-INF/config.xml 
  
  log_action_end_msg 0
  
  log_action_begin_msg "Apache James: add mail domains"
  
  fgrep mail.canistracci.oil SAR-INF/config.xml >/dev/null
  if [ "$?" != "0" ]; then
    sed -i '/<servername>localhost<\/servername>/ a\
         <servername>mail.canistracci.oil<\/servername>' SAR-INF/config.xml
  fi
  
  log_action_end_msg 0
  
  cd ~
  
  log_action_begin_msg "Apache James: configure as startup service"
  
  if [ ! -L /etc/rc0.d/K90apache-james ]; then
    if [ -f /etc/init.d/apache-james ]; then
      cp -p apache-james /etc/init.d
      chmod +x /etc/init.d/apache-james
      update-rc.d apache-james start 90 2 3 4 5 . stop 90 S 0 1 6 .
    fi
  fi
  
  log_action_end_msg 0
  
  log_success_msg "Apache James: ready for use"
}

#
# $1 the repository to check
#
check_apt_repository () {
  cat /etc/apt/sources.list | grep "^$1"
  return $?
}

# add and configure duplicity
duplicity () {
  CODENAME=`lsb_release -c | cut -f2 -d":" | sed 's/^\t*//;'`
  add_apt_repository "deb http://ppa.launchpad.net/duplicity-team/ppa/ubuntu ${CODENAME} main"
  
  apt-get install duplicity --yes --quiet
}

get_java_home () {
  log_action_begin_msg "Looking for JDK home"
  
  # The first existing directory is used for JAVA_HOME (if JAVA_HOME is not
  # defined in /etc/default/jetty). Should contain a list of space separated directories.
  JDK_DIRS="
  	  /usr/lib/jvm/default-java \
  	  /usr/lib/jvm/java-7-openjdk \
  	  /usr/lib/jvm/java-7-openjdk-i386 \
  	  /usr/lib/jvm/java-6-sun \
  	  /usr/lib/jvm/java-6-openjdk \
  	  /usr/lib/jvm/java-1.5.0-sun \
  	  /usr/lib/jvm/java-gcj \
  	  /usr/lib/j2sdk1.6-sun \
  	  /usr/lib/j2sdk1.5-sun \
  	  /usr/lib/j2sdk1.5-ibm \
  	  /usr/lib/j2sdk1.4-sun \
  	  /usr/lib/j2sdk1.4 \
  	  /usr/lib/j2se/1.4 \
  	  /usr/lib/kaffe/ \
  	 "
  # Look for the right JVM to use
  for jdir in $JDK_DIRS; do
  	if [ -d "$jdir" -a -z "${JAVA_HOME}" ]; then
  		JAVA_HOME="$jdir"
  	fi
  done
  export JAVA_HOME
  
  export JAVA="$JAVA_HOME/bin/java"
  
  if [ -x ${JAVA} ]; then
    log_action_end_msg 0
  else
    log_action_end_msg 1 "Cannot execute ${JAVA}"
    exit 1
  fi 
}

reprepro () {

  log_action_begin_msg "reprepro: installing software"
   
  if [ ! -x /usr/bin/reprepro ]; then
    apt-get install reprepro --yes --force-yes --quiet
  fi
   
  log_action_end_msg 0

  log_action_begin_msg "reprepro: create folders"
   
  # create the folders for the Ubuntu distributions
  mkdir -p /var/srv/reprepro/ubuntu/{conf,dists,incoming,indices,logs,pool,project,tmp}
   
  log_action_end_msg 0
  
  log_action_begin_msg "reprepro: configuration" 
  
  cat >/var/srv/reprepro/ubuntu/conf/distributions <<!
Origin: Petrol Package Repository
Label: Petrol Package Repository for Lucid
Codename: lucid
Architectures: i386 amd64 source
Components: non-free
Description: Locale Ubuntu 10.04 LTS repository
SignWith: yes

Origin: Petrol Package Repository
Label: Petrol Package Repository for Precise
Codename: precise
Architectures: i386 amd64 source
Components: non-free
Description: Locale Ubuntu 12.04 LTS Repository
SignWith: yes
!

  nano /var/srv/reprepro/ubuntu/conf/distributions
  
  log_action_end_msg 0
  
  cat > /var/srv/reprepro/ubuntu/conf/options <<!
verbose
basedir /var/srv/reprepro/ubuntu
ask-passphrase
!

}